# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d99534406bbec7be1014a1f98c694a9904c3c8fb863531c84e1e0d79b1edaf2194c6d1ff0baf35dbf192ec24f3cf2dd98b49e767ccbf409bf9242b26a5164ae

test:
  secret_key_base: 72319b4d9180f385ad200b7064991b598990b4c7d9534dd8e81bb18174879d82f03afd526753564ccd1b9482e72c444c700329aaec3eff97aa4792679f356c52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
